### PR TITLE
Rework of all metal dusts/ores/blocks and ingots

### PR DESCRIPTION
**Pull request by Klazkin**
Redrawing all and every sprite from scratch with the new style.
(well except for some armours xd)
------------------------------
- [x] Armours (item): 152/152
- [x] Armours (model) 78/78
- [x] Tools: 190/190
- [x] Gui: 2/2
- [ ] Blocks & Ores: 83/88 >currently working on
- [x] Tile entities: 12/12
- [x] Non-metals: 7/7
- [x] Ingots & dusts: 98/98
-------------------------------
**TOTAL:** 622/627 (99.2%)

### CODE REVIEW

**Comment by Davoleo** [comment]
I think the rework should be included all in one time. So that we don't have different styles at the same time, what do you think?
Was this intended to be a universal rework, or just a partial one?

**Comment by Klazkin** [comment]
I guess it was intended as a partial one, but it does make more sense to release it all at once.
I wished to get some feedback on the new colours, that's why I made this pull request.

**Comment by Davoleo** [comment]
woah, you really organized this PR well, thanks for your work Mat 💪

**Comment by Klazkin** [comment]
np tho the PR doesn't contain all of the changes above, i want to add tools all at once

**Comment by Klazkin** [comment]
510/625 (81.6%) So close :O

**Comment by Klazkin** [comment]
I'll Make a new one. Easier for me :PP

**Comment by Davoleo** [comment]
Well, that's easier for us too 👍

**Pull request closed without merging**
