### PR TITLE
Fixed alloyer shift click and hopper stuff

### PR DESCRIPTION
**Pull request by carbotaniuman**
This is a:
* Code Pull request

#### Description of the pull request content:
Fixed one part of Issue #23, fixed alloyer shift click, reworked SideEnum, made sure only valid items can be put in slots (only inputs in inputs, etc.)

### CODE REVIEW

**Comment by carbotaniuman** [comment]
Also used top for inputs, side for fuels, bottom for ouputs.

**Comment by Davoleo** [comment]
Going to test these code changes this afternoon 👍

**Comment by Davoleo** [comment]
When you shift click the coal, it goes in the input slot :P
@carbotaniuman 
image

**Comment by carbotaniuman** [comment]
@Davoleo just fixed

**Comment by Davoleo** [comment]
Merging right now

**Pull request merged**
